/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.common.processconfig;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class PROCESS_INFO extends PROCESS_INFOBase
{
    public PROCESS_INFO()
    {
        this((BusObjectConfig)null);
    }

    public PROCESS_INFO(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.laiyifen.common.processconfig.PROCESS_INFO> getAllPROCESS_INFO()
    {
    	String queryText = "select * from \"PROCESS_INFO\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(PROCESS_INFO.class);
        return query.getObjects();
    }

}
