/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.bpc.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class BPC_SUPPLIERSBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_SUPPLIERS_CODE = "SUPPLIERS_CODE";
    public final static String ATTR_SUPPLIERS_NAME = "SUPPLIERS_NAME";
    public final static String ATTR_BANKS = "BANKS";
    public final static String ATTR_NAMES = "NAMES";
    public final static String ATTR_BANK_ACCOUNT = "BANK_ACCOUNT";
    public final static String ATTR_BANK_NAME = "BANK_NAME";
    public final static String ATTR_CONTACT_NAME = "CONTACT_NAME";
    public final static String ATTR_CONTACT_PHONE = "CONTACT_PHONE";
    public final static String ATTR_EXT1 = "EXT1";
    public final static String ATTR_EXT2 = "EXT2";
    public final static String ATTR_EXT3 = "EXT3";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(BPC_SUPPLIERS.class);
            s_classInfo.setTableName("BPC_SUPPLIERS");
            s_classInfo.setUIDElements(new String[]{ATTR_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SUPPLIERS_CODE);
                ai.setJavaName(ATTR_SUPPLIERS_CODE);
                ai.setColumnName(ATTR_SUPPLIERS_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SUPPLIERS_CODE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SUPPLIERS_NAME);
                ai.setJavaName(ATTR_SUPPLIERS_NAME);
                ai.setColumnName(ATTR_SUPPLIERS_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SUPPLIERS_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BANKS);
                ai.setJavaName(ATTR_BANKS);
                ai.setColumnName(ATTR_BANKS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BANKS);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_NAMES);
                ai.setJavaName(ATTR_NAMES);
                ai.setColumnName(ATTR_NAMES);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_NAMES);
                v.setMaxLength(60);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BANK_ACCOUNT);
                ai.setJavaName(ATTR_BANK_ACCOUNT);
                ai.setColumnName(ATTR_BANK_ACCOUNT);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BANK_ACCOUNT);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BANK_NAME);
                ai.setJavaName(ATTR_BANK_NAME);
                ai.setColumnName(ATTR_BANK_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BANK_NAME);
                v.setMaxLength(60);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CONTACT_NAME);
                ai.setJavaName(ATTR_CONTACT_NAME);
                ai.setColumnName(ATTR_CONTACT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CONTACT_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CONTACT_PHONE);
                ai.setJavaName(ATTR_CONTACT_PHONE);
                ai.setColumnName(ATTR_CONTACT_PHONE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CONTACT_PHONE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT1);
                ai.setJavaName(ATTR_EXT1);
                ai.setColumnName(ATTR_EXT1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT2);
                ai.setJavaName(ATTR_EXT2);
                ai.setColumnName(ATTR_EXT2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT3);
                ai.setJavaName(ATTR_EXT3);
                ai.setColumnName(ATTR_EXT3);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT3);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public BPC_SUPPLIERSBase(BusObjectConfig config)
    {
        super(config);
    }

    public double getID()
    {
        return getDoubleProperty(ATTR_ID);
    }

    public void setID(double value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getSUPPLIERS_CODE()
    {
        return getStringProperty(ATTR_SUPPLIERS_CODE);
    }

    public void setSUPPLIERS_CODE(String value)
    {
        setProperty(ATTR_SUPPLIERS_CODE, value, 0);
    }

    public String getSUPPLIERS_NAME()
    {
        return getStringProperty(ATTR_SUPPLIERS_NAME);
    }

    public void setSUPPLIERS_NAME(String value)
    {
        setProperty(ATTR_SUPPLIERS_NAME, value, 0);
    }

    public String getBANKS()
    {
        return getStringProperty(ATTR_BANKS);
    }

    public void setBANKS(String value)
    {
        setProperty(ATTR_BANKS, value, 0);
    }

    public String getNAMES()
    {
        return getStringProperty(ATTR_NAMES);
    }

    public void setNAMES(String value)
    {
        setProperty(ATTR_NAMES, value, 0);
    }

    public String getBANK_ACCOUNT()
    {
        return getStringProperty(ATTR_BANK_ACCOUNT);
    }

    public void setBANK_ACCOUNT(String value)
    {
        setProperty(ATTR_BANK_ACCOUNT, value, 0);
    }

    public String getBANK_NAME()
    {
        return getStringProperty(ATTR_BANK_NAME);
    }

    public void setBANK_NAME(String value)
    {
        setProperty(ATTR_BANK_NAME, value, 0);
    }

    public String getCONTACT_NAME()
    {
        return getStringProperty(ATTR_CONTACT_NAME);
    }

    public void setCONTACT_NAME(String value)
    {
        setProperty(ATTR_CONTACT_NAME, value, 0);
    }

    public String getCONTACT_PHONE()
    {
        return getStringProperty(ATTR_CONTACT_PHONE);
    }

    public void setCONTACT_PHONE(String value)
    {
        setProperty(ATTR_CONTACT_PHONE, value, 0);
    }

    public String getEXT1()
    {
        return getStringProperty(ATTR_EXT1);
    }

    public void setEXT1(String value)
    {
        setProperty(ATTR_EXT1, value, 0);
    }

    public String getEXT2()
    {
        return getStringProperty(ATTR_EXT2);
    }

    public void setEXT2(String value)
    {
        setProperty(ATTR_EXT2, value, 0);
    }

    public String getEXT3()
    {
        return getStringProperty(ATTR_EXT3);
    }

    public void setEXT3(String value)
    {
        setProperty(ATTR_EXT3, value, 0);
    }

    public static com.laiyifen.bpc.core.BPC_SUPPLIERS getBpcSuppliersObject(double ID)
    {
        String queryText = "select * from \"BPC_SUPPLIERS\" where \"ID\" = :ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(ID));//NOPMD
        query.setResultClass(BPC_SUPPLIERS.class);
        return (BPC_SUPPLIERS)query.getObject();
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_SUPPLIERS> getBpcSuppliersObjects(double fromID, double toID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"BPC_SUPPLIERS\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(fromID));
        query.addParameter("toID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(toID));
        query.setResultClass(BPC_SUPPLIERS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_SUPPLIERS> getBpcSuppliersObjects(double fromID, double toID)
    {
        String queryText = "select * from \"BPC_SUPPLIERS\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(fromID));
        query.addParameter("toID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(toID));
        query.setResultClass(BPC_SUPPLIERS.class);
        return query.getObjects();
    }


    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_SUPPLIERS> getNextBpcSuppliersObjects(double ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"BPC_SUPPLIERS\" where (\"ID\" > :ID) order by \"ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(ID));//NOPMD
        query.setResultClass(BPC_SUPPLIERS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_SUPPLIERS> getPreviousBpcSuppliersObjects(double ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"BPC_SUPPLIERS\" where (\"ID\" < :ID) order by \"ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "BPC_SUPPLIERS.ID", QueryObject.PARAM_DOUBLE, new Double(ID));//NOPMD
        query.setResultClass(BPC_SUPPLIERS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }


}
