/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.bpc.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class BPC_TRAVEL_ITEMBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_FORM_ID = "FORM_ID";
    public final static String ATTR_START_ADDRESS = "START_ADDRESS";
    public final static String ATTR_END_ADDRESS = "END_ADDRESS";
    public final static String ATTR_START_TIME = "START_TIME";
    public final static String ATTR_END_TIME = "END_TIME";
    public final static String ATTR_TRAFFIC_TOOL = "TRAFFIC_TOOL";
    public final static String ATTR_TRAFFIC_SUM = "TRAFFIC_SUM";
    public final static String ATTR_FOOD_DAYS = "FOOD_DAYS";
    public final static String ATTR_FOOD_SUM = "FOOD_SUM";
    public final static String ATTR_LODGIN = "LODGIN";
    public final static String ATTR_CATERING = "CATERING";
    public final static String ATTR_OTHER_TYPE = "OTHER_TYPE";
    public final static String ATTR_OTHER_SUM = "OTHER_SUM";
    public final static String ATTR_REMARK = "REMARK";
    public final static String ATTR_SUBTOTAL = "SUBTOTAL";
    public final static String ATTR_SUBJECT_CODE = "SUBJECT_CODE";
    public final static String ATTR_SUBJECT_NAME = "SUBJECT_NAME";
    public final static String ATTR_ext1 = "ext1";
    public final static String ATTR_ext2 = "ext2";
    public final static String ATTR_ext3 = "ext3";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(BPC_TRAVEL_ITEM.class);
            s_classInfo.setTableName("BPC_TRAVEL_ITEM");
            s_classInfo.setUIDElements(new String[]{ATTR_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FORM_ID);
                ai.setJavaName(ATTR_FORM_ID);
                ai.setColumnName(ATTR_FORM_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FORM_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_START_ADDRESS);
                ai.setJavaName(ATTR_START_ADDRESS);
                ai.setColumnName(ATTR_START_ADDRESS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_START_ADDRESS);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_END_ADDRESS);
                ai.setJavaName(ATTR_END_ADDRESS);
                ai.setColumnName(ATTR_END_ADDRESS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_END_ADDRESS);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_START_TIME);
                ai.setJavaName(ATTR_START_TIME);
                ai.setColumnName(ATTR_START_TIME);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_END_TIME);
                ai.setJavaName(ATTR_END_TIME);
                ai.setColumnName(ATTR_END_TIME);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TRAFFIC_TOOL);
                ai.setJavaName(ATTR_TRAFFIC_TOOL);
                ai.setColumnName(ATTR_TRAFFIC_TOOL);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TRAFFIC_TOOL);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TRAFFIC_SUM);
                ai.setJavaName(ATTR_TRAFFIC_SUM);
                ai.setColumnName(ATTR_TRAFFIC_SUM);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_TRAFFIC_SUM);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FOOD_DAYS);
                ai.setJavaName(ATTR_FOOD_DAYS);
                ai.setColumnName(ATTR_FOOD_DAYS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FOOD_DAYS);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FOOD_SUM);
                ai.setJavaName(ATTR_FOOD_SUM);
                ai.setColumnName(ATTR_FOOD_SUM);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_FOOD_SUM);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LODGIN);
                ai.setJavaName(ATTR_LODGIN);
                ai.setColumnName(ATTR_LODGIN);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_LODGIN);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CATERING);
                ai.setJavaName(ATTR_CATERING);
                ai.setColumnName(ATTR_CATERING);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_CATERING);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OTHER_TYPE);
                ai.setJavaName(ATTR_OTHER_TYPE);
                ai.setColumnName(ATTR_OTHER_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OTHER_TYPE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OTHER_SUM);
                ai.setJavaName(ATTR_OTHER_SUM);
                ai.setColumnName(ATTR_OTHER_SUM);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_OTHER_SUM);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_REMARK);
                ai.setJavaName(ATTR_REMARK);
                ai.setColumnName(ATTR_REMARK);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_REMARK);
                v.setMaxLength(255);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SUBTOTAL);
                ai.setJavaName(ATTR_SUBTOTAL);
                ai.setColumnName(ATTR_SUBTOTAL);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_SUBTOTAL);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SUBJECT_CODE);
                ai.setJavaName(ATTR_SUBJECT_CODE);
                ai.setColumnName(ATTR_SUBJECT_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SUBJECT_CODE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SUBJECT_NAME);
                ai.setJavaName(ATTR_SUBJECT_NAME);
                ai.setColumnName(ATTR_SUBJECT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SUBJECT_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ext1);
                ai.setJavaName(ATTR_ext1);
                ai.setColumnName(ATTR_ext1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ext1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ext2);
                ai.setJavaName(ATTR_ext2);
                ai.setColumnName(ATTR_ext2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ext2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ext3);
                ai.setJavaName(ATTR_ext3);
                ai.setColumnName(ATTR_ext3);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ext3);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public BPC_TRAVEL_ITEMBase(BusObjectConfig config)
    {
        super(config);
    }

    public double getID()
    {
        return getDoubleProperty(ATTR_ID);
    }

    public void setID(double value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getFORM_ID()
    {
        return getStringProperty(ATTR_FORM_ID);
    }

    public void setFORM_ID(String value)
    {
        setProperty(ATTR_FORM_ID, value, 0);
    }

    public String getSTART_ADDRESS()
    {
        return getStringProperty(ATTR_START_ADDRESS);
    }

    public void setSTART_ADDRESS(String value)
    {
        setProperty(ATTR_START_ADDRESS, value, 0);
    }

    public String getEND_ADDRESS()
    {
        return getStringProperty(ATTR_END_ADDRESS);
    }

    public void setEND_ADDRESS(String value)
    {
        setProperty(ATTR_END_ADDRESS, value, 0);
    }

    public java.util.Date getSTART_TIME()
    {
        return getDateTimestampProperty(ATTR_START_TIME);
    }

    public void setSTART_TIME(java.util.Date value)
    {
        setProperty(ATTR_START_TIME, value, 0);
    }

    public java.util.Date getEND_TIME()
    {
        return getDateTimestampProperty(ATTR_END_TIME);
    }

    public void setEND_TIME(java.util.Date value)
    {
        setProperty(ATTR_END_TIME, value, 0);
    }

    public String getTRAFFIC_TOOL()
    {
        return getStringProperty(ATTR_TRAFFIC_TOOL);
    }

    public void setTRAFFIC_TOOL(String value)
    {
        setProperty(ATTR_TRAFFIC_TOOL, value, 0);
    }

    public double getTRAFFIC_SUM()
    {
        return getDoubleProperty(ATTR_TRAFFIC_SUM);
    }

    public void setTRAFFIC_SUM(double value)
    {
        setProperty(ATTR_TRAFFIC_SUM, value, 0);
    }

    public String getFOOD_DAYS()
    {
        return getStringProperty(ATTR_FOOD_DAYS);
    }

    public void setFOOD_DAYS(String value)
    {
        setProperty(ATTR_FOOD_DAYS, value, 0);
    }

    public double getFOOD_SUM()
    {
        return getDoubleProperty(ATTR_FOOD_SUM);
    }

    public void setFOOD_SUM(double value)
    {
        setProperty(ATTR_FOOD_SUM, value, 0);
    }

    public double getLODGIN()
    {
        return getDoubleProperty(ATTR_LODGIN);
    }

    public void setLODGIN(double value)
    {
        setProperty(ATTR_LODGIN, value, 0);
    }

    public double getCATERING()
    {
        return getDoubleProperty(ATTR_CATERING);
    }

    public void setCATERING(double value)
    {
        setProperty(ATTR_CATERING, value, 0);
    }

    public String getOTHER_TYPE()
    {
        return getStringProperty(ATTR_OTHER_TYPE);
    }

    public void setOTHER_TYPE(String value)
    {
        setProperty(ATTR_OTHER_TYPE, value, 0);
    }

    public double getOTHER_SUM()
    {
        return getDoubleProperty(ATTR_OTHER_SUM);
    }

    public void setOTHER_SUM(double value)
    {
        setProperty(ATTR_OTHER_SUM, value, 0);
    }

    public String getREMARK()
    {
        return getStringProperty(ATTR_REMARK);
    }

    public void setREMARK(String value)
    {
        setProperty(ATTR_REMARK, value, 0);
    }

    public double getSUBTOTAL()
    {
        return getDoubleProperty(ATTR_SUBTOTAL);
    }

    public void setSUBTOTAL(double value)
    {
        setProperty(ATTR_SUBTOTAL, value, 0);
    }

    public String getSUBJECT_CODE()
    {
        return getStringProperty(ATTR_SUBJECT_CODE);
    }

    public void setSUBJECT_CODE(String value)
    {
        setProperty(ATTR_SUBJECT_CODE, value, 0);
    }

    public String getSUBJECT_NAME()
    {
        return getStringProperty(ATTR_SUBJECT_NAME);
    }

    public void setSUBJECT_NAME(String value)
    {
        setProperty(ATTR_SUBJECT_NAME, value, 0);
    }

    public String getExt1()
    {
        return getStringProperty(ATTR_ext1);
    }

    public void setExt1(String value)
    {
        setProperty(ATTR_ext1, value, 0);
    }

    public String getExt2()
    {
        return getStringProperty(ATTR_ext2);
    }

    public void setExt2(String value)
    {
        setProperty(ATTR_ext2, value, 0);
    }

    public String getExt3()
    {
        return getStringProperty(ATTR_ext3);
    }

    public void setExt3(String value)
    {
        setProperty(ATTR_ext3, value, 0);
    }

    public static com.laiyifen.bpc.core.BPC_TRAVEL_ITEM getBpcTravelItemObject(double ID)
    {
        String queryText = "select * from \"BPC_TRAVEL_ITEM\" where \"ID\" = :ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(ID));//NOPMD
        query.setResultClass(BPC_TRAVEL_ITEM.class);
        return (BPC_TRAVEL_ITEM)query.getObject();
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_TRAVEL_ITEM> getBpcTravelItemObjects(double fromID, double toID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"BPC_TRAVEL_ITEM\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(fromID));
        query.addParameter("toID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(toID));
        query.setResultClass(BPC_TRAVEL_ITEM.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_TRAVEL_ITEM> getBpcTravelItemObjects(double fromID, double toID)
    {
        String queryText = "select * from \"BPC_TRAVEL_ITEM\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(fromID));
        query.addParameter("toID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(toID));
        query.setResultClass(BPC_TRAVEL_ITEM.class);
        return query.getObjects();
    }


    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_TRAVEL_ITEM> getNextBpcTravelItemObjects(double ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"BPC_TRAVEL_ITEM\" where (\"ID\" > :ID) order by \"ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(ID));//NOPMD
        query.setResultClass(BPC_TRAVEL_ITEM.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_TRAVEL_ITEM> getPreviousBpcTravelItemObjects(double ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"BPC_TRAVEL_ITEM\" where (\"ID\" < :ID) order by \"ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "BPC_TRAVEL_ITEM.ID", QueryObject.PARAM_DOUBLE, new Double(ID));//NOPMD
        query.setResultClass(BPC_TRAVEL_ITEM.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
