/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.bpc.core;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.event.AttributeInitializeEvent;
import com.laiyifen.common.core.APPROVAL_HISTORY;


public class BPC_FEEDEP extends BPC_FEEDEPBase
{
    public BPC_FEEDEP()
    {
        this((BusObjectConfig)null);
    }

    public BPC_FEEDEP(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.laiyifen.bpc.core.BPC_FEEDEP> getBpcFeedepObjectsByFormID(String formID)
    {
        // TODO implement body
    	 String queryText = "select * from \"BPC_FEEDEP\" where \"FORM_ID\" = :Form_ID";
         QueryObject query = new QueryObject(queryText);
         query.addParameter("Form_ID", "BPC_FEEDEP.FORM_ID", QueryObject.PARAM_STRING,formID);
         query.setResultClass(BPC_FEEDEP.class);
         return query.getObjects();
    }
    
    
}
