/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.bpc.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class CompositeBPCLoanInfoBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    private final static String REL_BPC_LOAN = "AGGR:BPC_LOAN";
    private final static String REL_BPC_LOAN_ITEM = "AGGR:BPC_LOAN_ITEM";
    private final static String REL_BPC_AUDIT = "AGGR:BPC_AUDIT";
    private final static String REL_APPROVAL_HISTORY = "AGGR:APPROVAL_HISTORY";
    private final static String REL_ATTACHMENT = "AGGR:ATTACHMENT";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(CompositeBPCLoanInfo.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_BPC_LOAN);
                ri.setName("BPC_LOAN");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.bpc.core.BPC_LOAN.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_BPC_LOAN_ITEM);
                ri.setName("BPC_LOAN_ITEM");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.laiyifen.bpc.core.BPC_LOAN_ITEM.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_BPC_AUDIT);
                ri.setName("BPC_AUDIT");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.bpc.core.BPC_AUDIT.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_APPROVAL_HISTORY);
                ri.setName("APPROVAL_HISTORY");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.laiyifen.common.core.APPROVAL_HISTORY.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_ATTACHMENT);
                ri.setName("ATTACHMENT");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.laiyifen.common.core.ATTACHMENT.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public CompositeBPCLoanInfoBase(BusObjectConfig config)
    {
        super(config);
    }

    public BPC_LOAN getBPC_LOANObject()
    {
        return (BPC_LOAN)getSingleRelationObject(REL_BPC_LOAN);
    }

    public BPC_LOAN setBPC_LOANObject(BPC_LOAN a_BPC_LOAN)
    {
        return(BPC_LOAN)_getSingleRelation(REL_BPC_LOAN, true).setLocalObject(a_BPC_LOAN);
    }

    public BusObjectIterator<BPC_LOAN_ITEM> getBPC_LOAN_ITEMObjects()
    {
        return getMultiRelationObjects(REL_BPC_LOAN_ITEM);
    }

    public BPC_LOAN_ITEM addBPC_LOAN_ITEMObject(BPC_LOAN_ITEM a_BPC_LOAN_ITEM)
    {
        return (BPC_LOAN_ITEM)_getMultiRelation(REL_BPC_LOAN_ITEM, true).addObject(a_BPC_LOAN_ITEM);
    }

    public void removeBPC_LOAN_ITEMObject(BPC_LOAN_ITEM a_BPC_LOAN_ITEM)
    {
        _getMultiRelation(REL_BPC_LOAN_ITEM, true).removeObject(a_BPC_LOAN_ITEM);
    }

    public BPC_AUDIT getBPC_AUDITObject()
    {
        return (BPC_AUDIT)getSingleRelationObject(REL_BPC_AUDIT);
    }

    public BPC_AUDIT setBPC_AUDITObject(BPC_AUDIT a_BPC_AUDIT)
    {
        return(BPC_AUDIT)_getSingleRelation(REL_BPC_AUDIT, true).setLocalObject(a_BPC_AUDIT);
    }

    public BusObjectIterator<com.laiyifen.common.core.APPROVAL_HISTORY> getAPPROVAL_HISTORYObjects()
    {
        return getMultiRelationObjects(REL_APPROVAL_HISTORY);
    }

    public com.laiyifen.common.core.APPROVAL_HISTORY addAPPROVAL_HISTORYObject(com.laiyifen.common.core.APPROVAL_HISTORY a_APPROVAL_HISTORY)
    {
        return (com.laiyifen.common.core.APPROVAL_HISTORY)_getMultiRelation(REL_APPROVAL_HISTORY, true).addObject(a_APPROVAL_HISTORY);
    }

    public void removeAPPROVAL_HISTORYObject(com.laiyifen.common.core.APPROVAL_HISTORY a_APPROVAL_HISTORY)
    {
        _getMultiRelation(REL_APPROVAL_HISTORY, true).removeObject(a_APPROVAL_HISTORY);
    }

    public BusObjectIterator<com.laiyifen.common.core.ATTACHMENT> getATTACHMENTObjects()
    {
        return getMultiRelationObjects(REL_ATTACHMENT);
    }

    public com.laiyifen.common.core.ATTACHMENT addATTACHMENTObject(com.laiyifen.common.core.ATTACHMENT a_ATTACHMENT)
    {
        return (com.laiyifen.common.core.ATTACHMENT)_getMultiRelation(REL_ATTACHMENT, true).addObject(a_ATTACHMENT);
    }

    public void removeATTACHMENTObject(com.laiyifen.common.core.ATTACHMENT a_ATTACHMENT)
    {
        _getMultiRelation(REL_ATTACHMENT, true).removeObject(a_ATTACHMENT);
    }



}
