/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.goods.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class GOODSCARDBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_FORM_ID = "FORM_ID";
    public final static String ATTR_ORDER_ID = "ORDER_ID";
    public final static String ATTR_PRODUCT_NAME = "PRODUCT_NAME";
    public final static String ATTR_GUIGE = "GUIGE";
    public final static String ATTR_DANJIA = "DANJIA";
    public final static String ATTR_JINER = "JINER";
    public final static String ATTR_SHULIANG = "SHULIANG";
    public final static String ATTR_FEIYONG = "FEIYONG";
    public final static String ATTR_HEJI = "HEJI";
    public final static String ATTR_BEIZHU = "BEIZHU";
    public final static String ATTR_ZONGJI = "ZONGJI";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(GOODSCARD.class);
            s_classInfo.setTableName("GOODSCARD");
            s_classInfo.setUIDElements(new String[]{ATTR_FORM_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FORM_ID);
                ai.setJavaName(ATTR_FORM_ID);
                ai.setColumnName(ATTR_FORM_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FORM_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ORDER_ID);
                ai.setJavaName(ATTR_ORDER_ID);
                ai.setColumnName(ATTR_ORDER_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ORDER_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_NAME);
                ai.setJavaName(ATTR_PRODUCT_NAME);
                ai.setColumnName(ATTR_PRODUCT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_NAME);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_GUIGE);
                ai.setJavaName(ATTR_GUIGE);
                ai.setColumnName(ATTR_GUIGE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_GUIGE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DANJIA);
                ai.setJavaName(ATTR_DANJIA);
                ai.setColumnName(ATTR_DANJIA);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_DANJIA);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_JINER);
                ai.setJavaName(ATTR_JINER);
                ai.setColumnName(ATTR_JINER);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_JINER);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SHULIANG);
                ai.setJavaName(ATTR_SHULIANG);
                ai.setColumnName(ATTR_SHULIANG);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_SHULIANG);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FEIYONG);
                ai.setJavaName(ATTR_FEIYONG);
                ai.setColumnName(ATTR_FEIYONG);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_FEIYONG);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_HEJI);
                ai.setJavaName(ATTR_HEJI);
                ai.setColumnName(ATTR_HEJI);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_HEJI);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BEIZHU);
                ai.setJavaName(ATTR_BEIZHU);
                ai.setColumnName(ATTR_BEIZHU);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BEIZHU);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ZONGJI);
                ai.setJavaName(ATTR_ZONGJI);
                ai.setColumnName(ATTR_ZONGJI);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_ZONGJI);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public GOODSCARDBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getFORM_ID()
    {
        return getStringProperty(ATTR_FORM_ID);
    }

    public void setFORM_ID(String value)
    {
        setProperty(ATTR_FORM_ID, value, 0);
    }

    public String getORDER_ID()
    {
        return getStringProperty(ATTR_ORDER_ID);
    }

    public void setORDER_ID(String value)
    {
        setProperty(ATTR_ORDER_ID, value, 0);
    }

    public String getPRODUCT_NAME()
    {
        return getStringProperty(ATTR_PRODUCT_NAME);
    }

    public void setPRODUCT_NAME(String value)
    {
        setProperty(ATTR_PRODUCT_NAME, value, 0);
    }

    public String getGUIGE()
    {
        return getStringProperty(ATTR_GUIGE);
    }

    public void setGUIGE(String value)
    {
        setProperty(ATTR_GUIGE, value, 0);
    }

    public double getDANJIA()
    {
        return getDoubleProperty(ATTR_DANJIA);
    }

    public void setDANJIA(double value)
    {
        setProperty(ATTR_DANJIA, value, 0);
    }

    public double getJINER()
    {
        return getDoubleProperty(ATTR_JINER);
    }

    public void setJINER(double value)
    {
        setProperty(ATTR_JINER, value, 0);
    }

    public double getSHULIANG()
    {
        return getDoubleProperty(ATTR_SHULIANG);
    }

    public void setSHULIANG(double value)
    {
        setProperty(ATTR_SHULIANG, value, 0);
    }

    public double getFEIYONG()
    {
        return getDoubleProperty(ATTR_FEIYONG);
    }

    public void setFEIYONG(double value)
    {
        setProperty(ATTR_FEIYONG, value, 0);
    }

    public double getHEJI()
    {
        return getDoubleProperty(ATTR_HEJI);
    }

    public void setHEJI(double value)
    {
        setProperty(ATTR_HEJI, value, 0);
    }

    public String getBEIZHU()
    {
        return getStringProperty(ATTR_BEIZHU);
    }

    public void setBEIZHU(String value)
    {
        setProperty(ATTR_BEIZHU, value, 0);
    }

    public double getZONGJI()
    {
        return getDoubleProperty(ATTR_ZONGJI);
    }

    public void setZONGJI(double value)
    {
        setProperty(ATTR_ZONGJI, value, 0);
    }

    public static com.laiyifen.goods.core.GOODSCARD getGoodscardObject(String FORM_ID)
    {
        String queryText = "select * from \"GOODSCARD\" where \"FORM_ID\" = :FORM_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("FORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, FORM_ID);//NOPMD
        query.setResultClass(GOODSCARD.class);
        return (GOODSCARD)query.getObject();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GOODSCARD> getGoodscardObjects(String fromFORM_ID, String toFORM_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"GOODSCARD\" where \"FORM_ID\" between :fromFORM_ID and :toFORM_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromFORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, fromFORM_ID);
        query.addParameter("toFORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, toFORM_ID);
        query.setResultClass(GOODSCARD.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GOODSCARD> getGoodscardObjects(String fromFORM_ID, String toFORM_ID)
    {
        String queryText = "select * from \"GOODSCARD\" where \"FORM_ID\" between :fromFORM_ID and :toFORM_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromFORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, fromFORM_ID);
        query.addParameter("toFORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, toFORM_ID);
        query.setResultClass(GOODSCARD.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GOODSCARD> getNextGoodscardObjects(String FORM_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"GOODSCARD\" where (\"FORM_ID\" > :FORM_ID) order by \"FORM_ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("FORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, FORM_ID);//NOPMD
        query.setResultClass(GOODSCARD.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GOODSCARD> getPreviousGoodscardObjects(String FORM_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"GOODSCARD\" where (\"FORM_ID\" < :FORM_ID) order by \"FORM_ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("FORM_ID", "GOODSCARD.FORM_ID", QueryObject.PARAM_STRING, FORM_ID);//NOPMD
        query.setResultClass(GOODSCARD.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
