/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.goods.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.util.logger.CordysLogger;
import com.eibus.util.logger.Severity;


public class GROUPBUY_MATERIAL_PRICE extends GROUPBUY_MATERIAL_PRICEBase
{
	private static CordysLogger logger = CordysLogger.getCordysLogger(GROUPBUY_MATERIAL_PRICE.class);
	
    public GROUPBUY_MATERIAL_PRICE()
    {
        this((BusObjectConfig)null);
    }

    public GROUPBUY_MATERIAL_PRICE(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GROUPBUY_MATERIAL_PRICE> getSelectGroupbuyMaterialPriceObjects(String saleOrgCode, String orderId, String productCode, String productName, String productType, com.cordys.cpc.bsf.query.Cursor cursor)
    {
    	logger.log(Severity.INFO, "getSelectGroupbuyMaterialPriceObjects--查询物料价格库存--开始", null);
    	
    	StringBuffer strBuf = new StringBuffer();
    	strBuf.append("select a.PRODUCT_CODE,a.SALE_ORG_CODE,a.PRICE,a.CURRENCY,a.COND_UNIT,a.SALES_UNIT,b.PRODUCT_NAME as ext1 " +
    			"from \"GROUPBUY_MATERIAL_PRICE\" a  right join \"GROUPBUY_MATERIAL_INFO\" b on a.product_code = b.product_code where a.\"PRODUCT_CODE\" not in (select PRODUCT_CODE from \"GROUPBUY_ORDER_DETAIL\" " +
    			"where \"ORDER_ID\" =:orderId and \"PRODUCT_TYPE\" =:productType) and a.\"PRODUCT_CODE\" = b.\"PRODUCT_CODE\" and a.\"SALE_ORG_CODE\" =:saleOrgCode ");
    	
    	 if (null != productCode && !("".equals(productCode)) && "" != productCode)
         {
         	strBuf.append("and b.\"PRODUCT_CODE\" like :productCode "); 
         }
    	 
    	 if (null != productName && !("".equals(productName)) && "" != productName)
         {
         	strBuf.append("and b.\"PRODUCT_NAME\" like :productName "); 
         }
    	 
    
        
        QueryObject query = new QueryObject(strBuf.toString());
        
        if (null != productCode && !("".equals(productCode)) && "" != productCode)
        {
        	query.addParameter("productCode", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, "%"+productCode+"%"); 
        }
   	 
   	 	if (null != productName && !("".equals(productName)) && "" != productName)
        {
   	 		query.addParameter("productName", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_NAME", QueryObject.PARAM_STRING, "%"+productName+"%"); 
        }
  
        query.addParameter("orderId", "GROUPBUY_ORDER_DETAIL.ORDER_ID", QueryObject.PARAM_STRING, orderId);
        query.addParameter("saleOrgCode", "GROUPBUY_MATERIAL_PRICE.SALE_ORG_CODE", QueryObject.PARAM_STRING, saleOrgCode);
        query.addParameter("productType", "GROUPBUY_ORDER_DETAIL.PRODUCT_TYPE", QueryObject.PARAM_STRING, productType);
        
        
        query.setResultClass(GROUPBUY_MATERIAL_PRICE.class);
        query.setCursor(cursor);
        
        
    	logger.log(Severity.INFO, "getSelectGroupbuyMaterialPriceObjects--查询物料价格库存--结束", null);
    	return query.getObjects();
    }

}
