/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.goods.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class GROUPBUY_MATERIAL_INVENTOBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_PRODUCT_CODE = "PRODUCT_CODE";
    public final static String ATTR_PRODUCT_NAME = "PRODUCT_NAME";
    public final static String ATTR_FACTORY = "FACTORY";
    public final static String ATTR_INVENTORY = "INVENTORY";
    public final static String ATTR_OA_INVENTORY = "OA_INVENTORY";
    public final static String ATTR_LST_UPDATE = "LST_UPDATE";
    public final static String ATTR_EXT1 = "EXT1";
    public final static String ATTR_EXT2 = "EXT2";
    public final static String ATTR_EXT3 = "EXT3";
    public final static String ATTR_EXT4 = "EXT4";
    public final static String ATTR_EXT5 = "EXT5";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(GROUPBUY_MATERIAL_INVENTO.class);
            s_classInfo.setTableName("GROUPBUY_MATERIAL_INVENTO");
            s_classInfo.setUIDElements(new String[]{ATTR_PRODUCT_CODE, ATTR_FACTORY});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_CODE);
                ai.setJavaName(ATTR_PRODUCT_CODE);
                ai.setColumnName(ATTR_PRODUCT_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_CODE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_NAME);
                ai.setJavaName(ATTR_PRODUCT_NAME);
                ai.setColumnName(ATTR_PRODUCT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FACTORY);
                ai.setJavaName(ATTR_FACTORY);
                ai.setColumnName(ATTR_FACTORY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FACTORY);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_INVENTORY);
                ai.setJavaName(ATTR_INVENTORY);
                ai.setColumnName(ATTR_INVENTORY);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_INVENTORY);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OA_INVENTORY);
                ai.setJavaName(ATTR_OA_INVENTORY);
                ai.setColumnName(ATTR_OA_INVENTORY);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_OA_INVENTORY);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LST_UPDATE);
                ai.setJavaName(ATTR_LST_UPDATE);
                ai.setColumnName(ATTR_LST_UPDATE);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT1);
                ai.setJavaName(ATTR_EXT1);
                ai.setColumnName(ATTR_EXT1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT2);
                ai.setJavaName(ATTR_EXT2);
                ai.setColumnName(ATTR_EXT2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT3);
                ai.setJavaName(ATTR_EXT3);
                ai.setColumnName(ATTR_EXT3);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT3);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT4);
                ai.setJavaName(ATTR_EXT4);
                ai.setColumnName(ATTR_EXT4);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT4);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT5);
                ai.setJavaName(ATTR_EXT5);
                ai.setColumnName(ATTR_EXT5);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT5);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public GROUPBUY_MATERIAL_INVENTOBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getPRODUCT_CODE()
    {
        return getStringProperty(ATTR_PRODUCT_CODE);
    }

    public void setPRODUCT_CODE(String value)
    {
        setProperty(ATTR_PRODUCT_CODE, value, 0);
    }

    public String getPRODUCT_NAME()
    {
        return getStringProperty(ATTR_PRODUCT_NAME);
    }

    public void setPRODUCT_NAME(String value)
    {
        setProperty(ATTR_PRODUCT_NAME, value, 0);
    }

    public String getFACTORY()
    {
        return getStringProperty(ATTR_FACTORY);
    }

    public void setFACTORY(String value)
    {
        setProperty(ATTR_FACTORY, value, 0);
    }

    public double getINVENTORY()
    {
        return getDoubleProperty(ATTR_INVENTORY);
    }

    public void setINVENTORY(double value)
    {
        setProperty(ATTR_INVENTORY, value, 0);
    }

    public double getOA_INVENTORY()
    {
        return getDoubleProperty(ATTR_OA_INVENTORY);
    }

    public void setOA_INVENTORY(double value)
    {
        setProperty(ATTR_OA_INVENTORY, value, 0);
    }

    public java.util.Date getLST_UPDATE()
    {
        return getDateTimestampProperty(ATTR_LST_UPDATE);
    }

    public void setLST_UPDATE(java.util.Date value)
    {
        setProperty(ATTR_LST_UPDATE, value, 0);
    }

    public String getEXT1()
    {
        return getStringProperty(ATTR_EXT1);
    }

    public void setEXT1(String value)
    {
        setProperty(ATTR_EXT1, value, 0);
    }

    public String getEXT2()
    {
        return getStringProperty(ATTR_EXT2);
    }

    public void setEXT2(String value)
    {
        setProperty(ATTR_EXT2, value, 0);
    }

    public String getEXT3()
    {
        return getStringProperty(ATTR_EXT3);
    }

    public void setEXT3(String value)
    {
        setProperty(ATTR_EXT3, value, 0);
    }

    public String getEXT4()
    {
        return getStringProperty(ATTR_EXT4);
    }

    public void setEXT4(String value)
    {
        setProperty(ATTR_EXT4, value, 0);
    }

    public String getEXT5()
    {
        return getStringProperty(ATTR_EXT5);
    }

    public void setEXT5(String value)
    {
        setProperty(ATTR_EXT5, value, 0);
    }

    public static com.laiyifen.goods.core.GROUPBUY_MATERIAL_INVENTO getGroupbuyMaterialInventoObject(String PRODUCT_CODE, String FACTORY)
    {
        String queryText = "select * from \"GROUPBUY_MATERIAL_INVENTO\" where \"PRODUCT_CODE\" = :PRODUCT_CODE and \"FACTORY\" = :FACTORY";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, PRODUCT_CODE);//NOPMD
        query.addParameter("FACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, FACTORY);//NOPMD
        query.setResultClass(GROUPBUY_MATERIAL_INVENTO.class);
        return (GROUPBUY_MATERIAL_INVENTO)query.getObject();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GROUPBUY_MATERIAL_INVENTO> getGroupbuyMaterialInventoObjects(String fromPRODUCT_CODE, String toPRODUCT_CODE, String fromFACTORY, String toFACTORY, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"GROUPBUY_MATERIAL_INVENTO\" where \"PRODUCT_CODE\" between :fromPRODUCT_CODE and :toPRODUCT_CODE and \"FACTORY\" between :fromFACTORY and :toFACTORY";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, fromPRODUCT_CODE);
        query.addParameter("toPRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, toPRODUCT_CODE);
        query.addParameter("fromFACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, fromFACTORY);
        query.addParameter("toFACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, toFACTORY);
        query.setResultClass(GROUPBUY_MATERIAL_INVENTO.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GROUPBUY_MATERIAL_INVENTO> getGroupbuyMaterialInventoObjects(String fromPRODUCT_CODE, String toPRODUCT_CODE, String fromFACTORY, String toFACTORY)
    {
        String queryText = "select * from \"GROUPBUY_MATERIAL_INVENTO\" where \"PRODUCT_CODE\" between :fromPRODUCT_CODE and :toPRODUCT_CODE and \"FACTORY\" between :fromFACTORY and :toFACTORY";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, fromPRODUCT_CODE);
        query.addParameter("toPRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, toPRODUCT_CODE);
        query.addParameter("fromFACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, fromFACTORY);
        query.addParameter("toFACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, toFACTORY);
        query.setResultClass(GROUPBUY_MATERIAL_INVENTO.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GROUPBUY_MATERIAL_INVENTO> getNextGroupbuyMaterialInventoObjects(String PRODUCT_CODE, String FACTORY, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"GROUPBUY_MATERIAL_INVENTO\" where (\"PRODUCT_CODE\" > :PRODUCT_CODE) or (\"PRODUCT_CODE\" = :PRODUCT_CODE and \"FACTORY\" > :FACTORY) order by \"PRODUCT_CODE\" asc, \"FACTORY\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, PRODUCT_CODE);//NOPMD
        query.addParameter("FACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, FACTORY);//NOPMD
        query.setResultClass(GROUPBUY_MATERIAL_INVENTO.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GROUPBUY_MATERIAL_INVENTO> getPreviousGroupbuyMaterialInventoObjects(String PRODUCT_CODE, String FACTORY, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"GROUPBUY_MATERIAL_INVENTO\" where (\"PRODUCT_CODE\" < :PRODUCT_CODE) or (\"PRODUCT_CODE\" = :PRODUCT_CODE and \"FACTORY\" < :FACTORY) order by \"PRODUCT_CODE\" desc, \"FACTORY\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PRODUCT_CODE", "GROUPBUY_MATERIAL_INVENTO.PRODUCT_CODE", QueryObject.PARAM_STRING, PRODUCT_CODE);//NOPMD
        query.addParameter("FACTORY", "GROUPBUY_MATERIAL_INVENTO.FACTORY", QueryObject.PARAM_STRING, FACTORY);//NOPMD
        query.setResultClass(GROUPBUY_MATERIAL_INVENTO.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
