/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.goods.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.util.logger.CordysLogger;
import com.eibus.util.logger.Severity;


public class GROUPBUY_CUSTOMER extends GROUPBUY_CUSTOMERBase
{
	private static CordysLogger logger = CordysLogger.getCordysLogger(GROUPBUY_CUSTOMER.class);
	
    public GROUPBUY_CUSTOMER()
    {
        this((BusObjectConfig)null);
    }

    public GROUPBUY_CUSTOMER(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.laiyifen.goods.core.GROUPBUY_CUSTOMER> getSelectGroupbuyCustomerObjects(String customerCode, String customerName, com.cordys.cpc.bsf.query.Cursor cursor)
    {
    	logger.log(Severity.INFO, "getSelectGroupbuyCustomerObjects--查询团购老客户--开始", null);
    	
    	StringBuffer strBuf = new StringBuffer();
    	strBuf.append("select * from \"GROUPBUY_CUSTOMER\" m where 1 = 1 ");
        
        if (null != customerCode && !("".equals(customerCode)) && "" != customerCode)
        {
        	strBuf.append("and m.\"CUSTOMER_CODE\" like :customerCode ");
        }
        if (null != customerName && !("".equals(customerName)) && "" != customerName)
        {
        	strBuf.append("and m.\"CUSTOMER_NAME\" like :customerName "); 
        }

        
        QueryObject query = new QueryObject(strBuf.toString());
        
        if (null != customerCode && !("".equals(customerCode)) && "" != customerCode)
        {
        	 query.addParameter("customerCode", "GROUPBUY_CUSTOMER.CUSTOMER_CODE", QueryObject.PARAM_STRING, "%"+customerCode+"%");
        }
        if (null != customerName && !("".equals(customerName)) && "" != customerName)
        {
        	 query.addParameter("customerName", "GROUPBUY_CUSTOMER.CUSTOMER_NAME", QueryObject.PARAM_STRING, "%"+customerName+"%");
        }
        
        
        query.setResultClass(GROUPBUY_CUSTOMER.class);
        query.setCursor(cursor);
        
        
    	logger.log(Severity.INFO, "getSelectGroupbuyCustomerObjects---查询团购老客户--结束", null);
    	return query.getObjects();
    }

}
