/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.common.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Assignment extends AssignmentBase
{
    public Assignment()
    {
        this((BusObjectConfig)null);
    }

    public Assignment(BusObjectConfig config)
    {
        super(config);
    }

    public static com.laiyifen.common.core.Assignment assignmentTask(String assignType, String assignConditon, String processCode, String companyCode)
    {
        // TODO implement body
        return null;
    }

    public static boolean syncParticipantInfo()
    {
        // TODO implement body
        return false;
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
