/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.common.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class AUTO_NUMBERBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_AUTO_SEQ = "AUTO_SEQ";
    public final static String ATTR_AUTO_TYPE = "AUTO_TYPE";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(AUTO_NUMBER.class);
            s_classInfo.setTableName("AUTO_NUMBER");
            s_classInfo.setUIDElements(new String[]{ATTR_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AUTO_SEQ);
                ai.setJavaName(ATTR_AUTO_SEQ);
                ai.setColumnName(ATTR_AUTO_SEQ);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AUTO_SEQ);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AUTO_TYPE);
                ai.setJavaName(ATTR_AUTO_TYPE);
                ai.setColumnName(ATTR_AUTO_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AUTO_TYPE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public AUTO_NUMBERBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getID()
    {
        return getStringProperty(ATTR_ID);
    }

    public void setID(String value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getAUTO_SEQ()
    {
        return getStringProperty(ATTR_AUTO_SEQ);
    }

    public void setAUTO_SEQ(String value)
    {
        setProperty(ATTR_AUTO_SEQ, value, 0);
    }

    public String getAUTO_TYPE()
    {
        return getStringProperty(ATTR_AUTO_TYPE);
    }

    public void setAUTO_TYPE(String value)
    {
        setProperty(ATTR_AUTO_TYPE, value, 0);
    }

    public static com.laiyifen.common.core.AUTO_NUMBER getAutoNumberObject(String ID)
    {
        String queryText = "select * from \"AUTO_NUMBER\" where \"ID\" = :ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, ID);//NOPMD
        query.setResultClass(AUTO_NUMBER.class);
        return (AUTO_NUMBER)query.getObject();
    }

    public static BusObjectIterator<com.laiyifen.common.core.AUTO_NUMBER> getAutoNumberObjects(String fromID, String toID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"AUTO_NUMBER\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, fromID);
        query.addParameter("toID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, toID);
        query.setResultClass(AUTO_NUMBER.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.common.core.AUTO_NUMBER> getAutoNumberObjects(String fromID, String toID)
    {
        String queryText = "select * from \"AUTO_NUMBER\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, fromID);
        query.addParameter("toID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, toID);
        query.setResultClass(AUTO_NUMBER.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.common.core.AUTO_NUMBER> getNextAutoNumberObjects(String ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"AUTO_NUMBER\" where (\"ID\" > :ID) order by \"ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, ID);//NOPMD
        query.setResultClass(AUTO_NUMBER.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.common.core.AUTO_NUMBER> getPreviousAutoNumberObjects(String ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"AUTO_NUMBER\" where (\"ID\" < :ID) order by \"ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "AUTO_NUMBER.ID", QueryObject.PARAM_STRING, ID);//NOPMD
        query.setResultClass(AUTO_NUMBER.class);
        query.setCursor(cursor);
        return query.getObjects();
    }


}
