/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.common.core;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class ORG_DEPARTMENT_INFO extends ORG_DEPARTMENT_INFOBase
{
    public ORG_DEPARTMENT_INFO()
    {
        this((BusObjectConfig)null);
    }

    public ORG_DEPARTMENT_INFO(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.laiyifen.common.core.ORG_DEPARTMENT_INFO> getAllOrgDepartmentInfo(com.cordys.cpc.bsf.query.Cursor cursor)
    {
    	String queryText = "SELECT * FROM \"ORG_DEPARTMENT_INFO\" ORDER BY \"DEPT_ID\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(ORG_DEPARTMENT_INFO.class);
        query.setCursor(cursor);
        return query.getObjects();
    }
    
    public static BusObjectIterator<com.laiyifen.common.core.ORG_DEPARTMENT_INFO> getChildDept(String DEPT_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
    	String queryText = "SELECT * FROM \"ORG_DEPARTMENT_INFO\" WHERE \"PARENT_ID\" = :PARENT_ID ORDER BY \"DEPT_ID\"";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PARENT_ID", "ORG_DEPARTMENT_INFO.PARENT_ID", QueryObject.PARAM_STRING, DEPT_ID);
        query.setResultClass(ORG_DEPARTMENT_INFO.class);
        query.setCursor(cursor);
        return query.getObjects();
    }
    
    public static BusObjectIterator<com.laiyifen.common.core.ORG_DEPARTMENT_INFO> getOrgDepartmentInfoByFilters(String DEPT_ID, String DEPT_NAME, String PARENT_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
    	String queryText = "SELECT * FROM ORG_DEPARTMENT_INFO WHERE 1=1";
    	if(DEPT_ID.equals("") != true){
        	queryText += "AND DEPT_ID = '" +DEPT_ID+"'";
        }
    	if(DEPT_NAME.equals("") != true){
        	queryText += "AND DEPT_NAME LIKE '%" +DEPT_NAME+"%'";
        }
    	if(PARENT_ID.equals("") != true){
        	queryText += "AND PARENT_ID = '" +PARENT_ID+"'";
        }
    	QueryObject query = new QueryObject(queryText);
        query.setResultClass(ORG_DEPARTMENT_INFO.class);
        query.setCursor(cursor);
        return query.getObjects();
    }
}