/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.shop;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class CompositeShopTargetInfoBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    private final static String REL_SHOP_TARGET_INFO = "AGGR:SHOP_TARGET_INFO";
    private final static String REL_SHOP_TARGET_CHECK = "AGGR:SHOP_TARGET_CHECK";
    private final static String REL_SHOP_TARGET_ESTIMATION = "AGGR:SHOP_TARGET_ESTIMATION";
    private final static String REL_SHOP_TARGET_CIRCLE_INFO = "AGGR:SHOP_TARGET_CIRCLE_INFO";
    private final static String REL_SHOP_TARGET_ASSESMENT = "AGGR:SHOP_TARGET_ASSESMENT";
    private final static String REL_ATTACHMENT = "AGGR:ATTACHMENT";
    private final static String REL_APPROVAL_HISTORY = "AGGR:APPROVAL_HISTORY";
    private final static String REL_SHOP_MASTER = "AGGR:SHOP_MASTER";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(CompositeShopTargetInfo.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_SHOP_TARGET_INFO);
                ri.setName("SHOP_TARGET_INFO");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.shop.SHOP_TARGET_INFO.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_SHOP_TARGET_CHECK);
                ri.setName("SHOP_TARGET_CHECK");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.shop.SHOP_TARGET_CHECK.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_SHOP_TARGET_ESTIMATION);
                ri.setName("SHOP_TARGET_ESTIMATION");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.laiyifen.shop.SHOP_TARGET_ESTIMATION.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_SHOP_TARGET_CIRCLE_INFO);
                ri.setName("SHOP_TARGET_CIRCLE_INFO");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.shop.SHOP_TARGET_CIRCLE_INFO.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_SHOP_TARGET_ASSESMENT);
                ri.setName("SHOP_TARGET_ASSESMENT");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.shop.SHOP_TARGET_ASSESMENT.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_ATTACHMENT);
                ri.setName("ATTACHMENT");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.laiyifen.common.core.ATTACHMENT.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_APPROVAL_HISTORY);
                ri.setName("APPROVAL_HISTORY");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.laiyifen.common.core.APPROVAL_HISTORY.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_SHOP_MASTER);
                ri.setName("SHOP_MASTER");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.laiyifen.shop.SHOP_MASTER.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public CompositeShopTargetInfoBase(BusObjectConfig config)
    {
        super(config);
    }

    public SHOP_TARGET_INFO getSHOP_TARGET_INFOObject()
    {
        return (SHOP_TARGET_INFO)getSingleRelationObject(REL_SHOP_TARGET_INFO);
    }

    public SHOP_TARGET_INFO setSHOP_TARGET_INFOObject(SHOP_TARGET_INFO a_SHOP_TARGET_INFO)
    {
        return(SHOP_TARGET_INFO)_getSingleRelation(REL_SHOP_TARGET_INFO, true).setLocalObject(a_SHOP_TARGET_INFO);
    }

    public SHOP_TARGET_CHECK getSHOP_TARGET_CHECKObject()
    {
        return (SHOP_TARGET_CHECK)getSingleRelationObject(REL_SHOP_TARGET_CHECK);
    }

    public SHOP_TARGET_CHECK setSHOP_TARGET_CHECKObject(SHOP_TARGET_CHECK a_SHOP_TARGET_CHECK)
    {
        return(SHOP_TARGET_CHECK)_getSingleRelation(REL_SHOP_TARGET_CHECK, true).setLocalObject(a_SHOP_TARGET_CHECK);
    }

    public BusObjectIterator<SHOP_TARGET_ESTIMATION> getSHOP_TARGET_ESTIMATIONObjects()
    {
        return getMultiRelationObjects(REL_SHOP_TARGET_ESTIMATION);
    }

    public SHOP_TARGET_ESTIMATION addSHOP_TARGET_ESTIMATIONObject(SHOP_TARGET_ESTIMATION a_SHOP_TARGET_ESTIMATION)
    {
        return (SHOP_TARGET_ESTIMATION)_getMultiRelation(REL_SHOP_TARGET_ESTIMATION, true).addObject(a_SHOP_TARGET_ESTIMATION);
    }

    public void removeSHOP_TARGET_ESTIMATIONObject(SHOP_TARGET_ESTIMATION a_SHOP_TARGET_ESTIMATION)
    {
        _getMultiRelation(REL_SHOP_TARGET_ESTIMATION, true).removeObject(a_SHOP_TARGET_ESTIMATION);
    }

    public SHOP_TARGET_CIRCLE_INFO getSHOP_TARGET_CIRCLE_INFOObject()
    {
        return (SHOP_TARGET_CIRCLE_INFO)getSingleRelationObject(REL_SHOP_TARGET_CIRCLE_INFO);
    }

    public SHOP_TARGET_CIRCLE_INFO setSHOP_TARGET_CIRCLE_INFOObject(SHOP_TARGET_CIRCLE_INFO a_SHOP_TARGET_CIRCLE_INFO)
    {
        return(SHOP_TARGET_CIRCLE_INFO)_getSingleRelation(REL_SHOP_TARGET_CIRCLE_INFO, true).setLocalObject(a_SHOP_TARGET_CIRCLE_INFO);
    }

    public SHOP_TARGET_ASSESMENT getSHOP_TARGET_ASSESMENTObject()
    {
        return (SHOP_TARGET_ASSESMENT)getSingleRelationObject(REL_SHOP_TARGET_ASSESMENT);
    }

    public SHOP_TARGET_ASSESMENT setSHOP_TARGET_ASSESMENTObject(SHOP_TARGET_ASSESMENT a_SHOP_TARGET_ASSESMENT)
    {
        return(SHOP_TARGET_ASSESMENT)_getSingleRelation(REL_SHOP_TARGET_ASSESMENT, true).setLocalObject(a_SHOP_TARGET_ASSESMENT);
    }

    public BusObjectIterator<com.laiyifen.common.core.ATTACHMENT> getATTACHMENTObjects()
    {
        return getMultiRelationObjects(REL_ATTACHMENT);
    }

    public com.laiyifen.common.core.ATTACHMENT addATTACHMENTObject(com.laiyifen.common.core.ATTACHMENT a_ATTACHMENT)
    {
        return (com.laiyifen.common.core.ATTACHMENT)_getMultiRelation(REL_ATTACHMENT, true).addObject(a_ATTACHMENT);
    }

    public void removeATTACHMENTObject(com.laiyifen.common.core.ATTACHMENT a_ATTACHMENT)
    {
        _getMultiRelation(REL_ATTACHMENT, true).removeObject(a_ATTACHMENT);
    }

    public BusObjectIterator<com.laiyifen.common.core.APPROVAL_HISTORY> getAPPROVAL_HISTORYObjects()
    {
        return getMultiRelationObjects(REL_APPROVAL_HISTORY);
    }

    public com.laiyifen.common.core.APPROVAL_HISTORY addAPPROVAL_HISTORYObject(com.laiyifen.common.core.APPROVAL_HISTORY a_APPROVAL_HISTORY)
    {
        return (com.laiyifen.common.core.APPROVAL_HISTORY)_getMultiRelation(REL_APPROVAL_HISTORY, true).addObject(a_APPROVAL_HISTORY);
    }

    public void removeAPPROVAL_HISTORYObject(com.laiyifen.common.core.APPROVAL_HISTORY a_APPROVAL_HISTORY)
    {
        _getMultiRelation(REL_APPROVAL_HISTORY, true).removeObject(a_APPROVAL_HISTORY);
    }

    public SHOP_MASTER getSHOP_MASTERObject()
    {
        return (SHOP_MASTER)getSingleRelationObject(REL_SHOP_MASTER);
    }

    public SHOP_MASTER setSHOP_MASTERObject(SHOP_MASTER a_SHOP_MASTER)
    {
        return(SHOP_MASTER)_getSingleRelation(REL_SHOP_MASTER, true).setLocalObject(a_SHOP_MASTER);
    }


}
