/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.shop;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class MATERIAL_AVER_PRICEBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_PRODUCT_CODE = "PRODUCT_CODE";
    public final static String ATTR_PRODUCT_NAME = "PRODUCT_NAME";
    public final static String ATTR_EFFECT_DATE = "EFFECT_DATE";
    public final static String ATTR_STATUS = "STATUS";
    public final static String ATTR_PRICE = "PRICE";
    public final static String ATTR_LST_UPDATE = "LST_UPDATE";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(MATERIAL_AVER_PRICE.class);
            s_classInfo.setTableName("MATERIAL_AVER_PRICE");
            s_classInfo.setUIDElements(new String[]{ATTR_PRODUCT_CODE});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_CODE);
                ai.setJavaName(ATTR_PRODUCT_CODE);
                ai.setColumnName(ATTR_PRODUCT_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_CODE);
                v.setMaxLength(18);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_NAME);
                ai.setJavaName(ATTR_PRODUCT_NAME);
                ai.setColumnName(ATTR_PRODUCT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EFFECT_DATE);
                ai.setJavaName(ATTR_EFFECT_DATE);
                ai.setColumnName(ATTR_EFFECT_DATE);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATUS);
                ai.setJavaName(ATTR_STATUS);
                ai.setColumnName(ATTR_STATUS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATUS);
                v.setMaxLength(2);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRICE);
                ai.setJavaName(ATTR_PRICE);
                ai.setColumnName(ATTR_PRICE);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_PRICE);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LST_UPDATE);
                ai.setJavaName(ATTR_LST_UPDATE);
                ai.setColumnName(ATTR_LST_UPDATE);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public MATERIAL_AVER_PRICEBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getPRODUCT_CODE()
    {
        return getStringProperty(ATTR_PRODUCT_CODE);
    }

    public void setPRODUCT_CODE(String value)
    {
        setProperty(ATTR_PRODUCT_CODE, value, 0);
    }

    public String getPRODUCT_NAME()
    {
        return getStringProperty(ATTR_PRODUCT_NAME);
    }

    public void setPRODUCT_NAME(String value)
    {
        setProperty(ATTR_PRODUCT_NAME, value, 0);
    }

    public java.util.Date getEFFECT_DATE()
    {
        return getDateTimestampProperty(ATTR_EFFECT_DATE);
    }

    public void setEFFECT_DATE(java.util.Date value)
    {
        setProperty(ATTR_EFFECT_DATE, value, 0);
    }

    public String getSTATUS()
    {
        return getStringProperty(ATTR_STATUS);
    }

    public void setSTATUS(String value)
    {
        setProperty(ATTR_STATUS, value, 0);
    }

    public double getPRICE()
    {
        return getDoubleProperty(ATTR_PRICE);
    }

    public void setPRICE(double value)
    {
        setProperty(ATTR_PRICE, value, 0);
    }

    public java.util.Date getLST_UPDATE()
    {
        return getDateTimestampProperty(ATTR_LST_UPDATE);
    }

    public void setLST_UPDATE(java.util.Date value)
    {
        setProperty(ATTR_LST_UPDATE, value, 0);
    }


    public static com.laiyifen.shop.MATERIAL_AVER_PRICE getMaterialAverPriceObject(String PRODUCT_CODE)
    {
        String queryText = "select * from \"MATERIAL_AVER_PRICE\" where \"PRODUCT_CODE\" = :PRODUCT_CODE";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, PRODUCT_CODE);//NOPMD
        query.setResultClass(MATERIAL_AVER_PRICE.class);
        return (MATERIAL_AVER_PRICE)query.getObject();
    }

    public static BusObjectIterator<com.laiyifen.shop.MATERIAL_AVER_PRICE> getMaterialAverPriceObjects(String fromPRODUCT_CODE, String toPRODUCT_CODE, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MATERIAL_AVER_PRICE\" where \"PRODUCT_CODE\" between :fromPRODUCT_CODE and :toPRODUCT_CODE";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, fromPRODUCT_CODE);
        query.addParameter("toPRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, toPRODUCT_CODE);
        query.setResultClass(MATERIAL_AVER_PRICE.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.shop.MATERIAL_AVER_PRICE> getMaterialAverPriceObjects(String fromPRODUCT_CODE, String toPRODUCT_CODE)
    {
        String queryText = "select * from \"MATERIAL_AVER_PRICE\" where \"PRODUCT_CODE\" between :fromPRODUCT_CODE and :toPRODUCT_CODE";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, fromPRODUCT_CODE);
        query.addParameter("toPRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, toPRODUCT_CODE);
        query.setResultClass(MATERIAL_AVER_PRICE.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.shop.MATERIAL_AVER_PRICE> getNextMaterialAverPriceObjects(String PRODUCT_CODE, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MATERIAL_AVER_PRICE\" where (\"PRODUCT_CODE\" > :PRODUCT_CODE) order by \"PRODUCT_CODE\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, PRODUCT_CODE);//NOPMD
        query.setResultClass(MATERIAL_AVER_PRICE.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.shop.MATERIAL_AVER_PRICE> getPreviousMaterialAverPriceObjects(String PRODUCT_CODE, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MATERIAL_AVER_PRICE\" where (\"PRODUCT_CODE\" < :PRODUCT_CODE) order by \"PRODUCT_CODE\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PRODUCT_CODE", "MATERIAL_AVER_PRICE.PRODUCT_CODE", QueryObject.PARAM_STRING, PRODUCT_CODE);//NOPMD
        query.setResultClass(MATERIAL_AVER_PRICE.class);
        query.setCursor(cursor);
        return query.getObjects();
    }


}
