/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.shop;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.laiyifen.shop.util.ShopMasterUtil;


public class SHOP_MASTER extends SHOP_MASTERBase
{
    public SHOP_MASTER()
    {
        this((BusObjectConfig)null);
    }

    public SHOP_MASTER(BusObjectConfig config)
    {
        super(config);
    }

    public static String getMDMShopId(String areaName, String branchType)
    {
        return ShopMasterUtil.getMDMShopId(areaName, branchType);
    }

    public static String getShopId()
    {
        // TODO implement body
        return ShopMasterUtil.getShopId();
    }

    public static BusObjectIterator<com.laiyifen.shop.SHOP_MASTER> getShopMasterByShopNo(String SHOP_NO)
    {
    	String queryText = "select * from \"SHOP_MASTER\" where \"SHOP_NO\" =:SHOP_NO ";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SHOP_NO", "SHOP_MASTER.SHOP_NO", QueryObject.PARAM_STRING, SHOP_NO);
        query.setResultClass(SHOP_MASTER.class);
        return query.getObjects();
    }

    public static String getShopName(String district, String street, String mallName)
    {
        // TODO implement body
        return ShopMasterUtil.getShopName(district, street, mallName);
    }

}