/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.shop;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class SHOP_MASTER_ENGDEPTBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SHOP_ID = "SHOP_ID";
    public final static String ATTR_FORM_ID = "FORM_ID";
    public final static String ATTR_USER_NAME = "USER_NAME";
    public final static String ATTR_USER_CODE = "USER_CODE";
    public final static String ATTR_DEPARTMENT_CODE = "DEPARTMENT_CODE";
    public final static String ATTR_DEPARTMENT_NAME = "DEPARTMENT_NAME";
    public final static String ATTR_COMPANY_CODE = "COMPANY_CODE";
    public final static String ATTR_COMPANY_NAME = "COMPANY_NAME";
    public final static String ATTR_APPLICATION_DATE = "APPLICATION_DATE";
    public final static String ATTR_ONEROOM = "ONEROOM";
    public final static String ATTR_ONEROOM_NAME = "ONEROOM_NAME";
    public final static String ATTR_BUSINESS_SPACE = "BUSINESS_SPACE";
    public final static String ATTR_AFTER_WAREHOUSE_AREA = "AFTER_WAREHOUSE_AREA";
    public final static String ATTR_COUNTER_TO_DOOR = "COUNTER_TO_DOOR";
    public final static String ATTR_POSITIVE_DIRECTION = "POSITIVE_DIRECTION";
    public final static String ATTR_POSITIVE_DIRECTIONNAME = "POSITIVE_DIRECTIONNAME";
    public final static String ATTR_HIGH_CABINTE_NO = "HIGH_CABINTE_NO";
    public final static String ATTR_SHOP_CABINTE_NO = "SHOP_CABINTE_NO";
    public final static String ATTR_AATROUGH_NO = "AATROUGH_NO";
    public final static String ATTR_BACK_CABINET_NO = "BACK_CABINET_NO";
    public final static String ATTR_SIDE_LIGHT_BOX_SIZE = "SIDE_LIGHT_BOX_SIZE";
    public final static String ATTR_DOOR_LIGHT_BOX_SIZE = "DOOR_LIGHT_BOX_SIZE";
    public final static String ATTR_ADVERTISEMENT_LOCATION = "ADVERTISEMENT_LOCATION";
    public final static String ATTR_LATTICE_NO = "LATTICE_NO";
    public final static String ATTR_ENTRANCE_NO = "ENTRANCE_NO";
    public final static String ATTR_DECORATION_END_DATE = "DECORATION_END_DATE";
    public final static String ATTR_DECORATION_STYLE = "DECORATION_STYLE";
    public final static String ATTR_DECORATION_STYLENAME = "DECORATION_STYLENAME";
    public final static String ATTR_CABINTE_LAYOUT_STYLE = "CABINTE_LAYOUT_STYLE";
    public final static String ATTR_CABINTE_LAYOUTSTYLENAME = "CABINTE_LAYOUTSTYLENAME";
    public final static String ATTR_TEAM_DECORATION = "TEAM_DECORATION";
    public final static String ATTR_CANOPY_SUPPLIER = "CANOPY_SUPPLIER";
    public final static String ATTR_AIR_CONDITIONING_SUPPLIER = "AIR_CONDITIONING_SUPPLIER";
    public final static String ATTR_LIGHT_BOX_SUPPLIER = "LIGHT_BOX_SUPPLIER";
    public final static String ATTR_CABINTE_SUPPLIER = "CABINTE_SUPPLIER";
    public final static String ATTR_LED_SCREEN_SUPPLIER = "LED_SCREEN_SUPPLIER";
    public final static String ATTR_CHECKOUT_SUPPLIER = "CHECKOUT_SUPPLIER";
    public final static String ATTR_AUTOMATIC_DOOR_SUPPLIER = "AUTOMATIC_DOOR_SUPPLIER";
    public final static String ATTR_SHUTTER_DOOR_SUPPLIER = "SHUTTER_DOOR_SUPPLIER";
    public final static String ATTR_EXT1 = "EXT1";
    public final static String ATTR_SHOP_VOLUME = "SHOP_VOLUME";
    public final static String ATTR_EXT2 = "EXT2";
    public final static String ATTR_STATUS = "STATUS";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(SHOP_MASTER_ENGDEPT.class);
            s_classInfo.setTableName("SHOP_MASTER_ENGDEPT");
            s_classInfo.setUIDElements(new String[]{ATTR_FORM_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SHOP_ID);
                ai.setJavaName(ATTR_SHOP_ID);
                ai.setColumnName(ATTR_SHOP_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SHOP_ID);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FORM_ID);
                ai.setJavaName(ATTR_FORM_ID);
                ai.setColumnName(ATTR_FORM_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FORM_ID);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USER_NAME);
                ai.setJavaName(ATTR_USER_NAME);
                ai.setColumnName(ATTR_USER_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USER_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USER_CODE);
                ai.setJavaName(ATTR_USER_CODE);
                ai.setColumnName(ATTR_USER_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USER_CODE);
                v.setMaxLength(8);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DEPARTMENT_CODE);
                ai.setJavaName(ATTR_DEPARTMENT_CODE);
                ai.setColumnName(ATTR_DEPARTMENT_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DEPARTMENT_CODE);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DEPARTMENT_NAME);
                ai.setJavaName(ATTR_DEPARTMENT_NAME);
                ai.setColumnName(ATTR_DEPARTMENT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DEPARTMENT_NAME);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_COMPANY_CODE);
                ai.setJavaName(ATTR_COMPANY_CODE);
                ai.setColumnName(ATTR_COMPANY_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_COMPANY_CODE);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_COMPANY_NAME);
                ai.setJavaName(ATTR_COMPANY_NAME);
                ai.setColumnName(ATTR_COMPANY_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_COMPANY_NAME);
                v.setMaxLength(8);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_APPLICATION_DATE);
                ai.setJavaName(ATTR_APPLICATION_DATE);
                ai.setColumnName(ATTR_APPLICATION_DATE);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ONEROOM);
                ai.setJavaName(ATTR_ONEROOM);
                ai.setColumnName(ATTR_ONEROOM);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ONEROOM);
                v.setMaxLength(2);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ONEROOM_NAME);
                ai.setJavaName(ATTR_ONEROOM_NAME);
                ai.setColumnName(ATTR_ONEROOM_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ONEROOM_NAME);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BUSINESS_SPACE);
                ai.setJavaName(ATTR_BUSINESS_SPACE);
                ai.setColumnName(ATTR_BUSINESS_SPACE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BUSINESS_SPACE);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AFTER_WAREHOUSE_AREA);
                ai.setJavaName(ATTR_AFTER_WAREHOUSE_AREA);
                ai.setColumnName(ATTR_AFTER_WAREHOUSE_AREA);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AFTER_WAREHOUSE_AREA);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_COUNTER_TO_DOOR);
                ai.setJavaName(ATTR_COUNTER_TO_DOOR);
                ai.setColumnName(ATTR_COUNTER_TO_DOOR);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_COUNTER_TO_DOOR);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_POSITIVE_DIRECTION);
                ai.setJavaName(ATTR_POSITIVE_DIRECTION);
                ai.setColumnName(ATTR_POSITIVE_DIRECTION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_POSITIVE_DIRECTION);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_POSITIVE_DIRECTIONNAME);
                ai.setJavaName(ATTR_POSITIVE_DIRECTIONNAME);
                ai.setColumnName(ATTR_POSITIVE_DIRECTIONNAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_POSITIVE_DIRECTIONNAME);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_HIGH_CABINTE_NO);
                ai.setJavaName(ATTR_HIGH_CABINTE_NO);
                ai.setColumnName(ATTR_HIGH_CABINTE_NO);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_HIGH_CABINTE_NO);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SHOP_CABINTE_NO);
                ai.setJavaName(ATTR_SHOP_CABINTE_NO);
                ai.setColumnName(ATTR_SHOP_CABINTE_NO);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SHOP_CABINTE_NO);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AATROUGH_NO);
                ai.setJavaName(ATTR_AATROUGH_NO);
                ai.setColumnName(ATTR_AATROUGH_NO);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AATROUGH_NO);
                v.setMaxLength(25);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BACK_CABINET_NO);
                ai.setJavaName(ATTR_BACK_CABINET_NO);
                ai.setColumnName(ATTR_BACK_CABINET_NO);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BACK_CABINET_NO);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SIDE_LIGHT_BOX_SIZE);
                ai.setJavaName(ATTR_SIDE_LIGHT_BOX_SIZE);
                ai.setColumnName(ATTR_SIDE_LIGHT_BOX_SIZE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SIDE_LIGHT_BOX_SIZE);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DOOR_LIGHT_BOX_SIZE);
                ai.setJavaName(ATTR_DOOR_LIGHT_BOX_SIZE);
                ai.setColumnName(ATTR_DOOR_LIGHT_BOX_SIZE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DOOR_LIGHT_BOX_SIZE);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ADVERTISEMENT_LOCATION);
                ai.setJavaName(ATTR_ADVERTISEMENT_LOCATION);
                ai.setColumnName(ATTR_ADVERTISEMENT_LOCATION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ADVERTISEMENT_LOCATION);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LATTICE_NO);
                ai.setJavaName(ATTR_LATTICE_NO);
                ai.setColumnName(ATTR_LATTICE_NO);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_LATTICE_NO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ENTRANCE_NO);
                ai.setJavaName(ATTR_ENTRANCE_NO);
                ai.setColumnName(ATTR_ENTRANCE_NO);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_ENTRANCE_NO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DECORATION_END_DATE);
                ai.setJavaName(ATTR_DECORATION_END_DATE);
                ai.setColumnName(ATTR_DECORATION_END_DATE);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DECORATION_STYLE);
                ai.setJavaName(ATTR_DECORATION_STYLE);
                ai.setColumnName(ATTR_DECORATION_STYLE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DECORATION_STYLE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DECORATION_STYLENAME);
                ai.setJavaName(ATTR_DECORATION_STYLENAME);
                ai.setColumnName(ATTR_DECORATION_STYLENAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DECORATION_STYLENAME);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CABINTE_LAYOUT_STYLE);
                ai.setJavaName(ATTR_CABINTE_LAYOUT_STYLE);
                ai.setColumnName(ATTR_CABINTE_LAYOUT_STYLE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CABINTE_LAYOUT_STYLE);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CABINTE_LAYOUTSTYLENAME);
                ai.setJavaName(ATTR_CABINTE_LAYOUTSTYLENAME);
                ai.setColumnName(ATTR_CABINTE_LAYOUTSTYLENAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CABINTE_LAYOUTSTYLENAME);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TEAM_DECORATION);
                ai.setJavaName(ATTR_TEAM_DECORATION);
                ai.setColumnName(ATTR_TEAM_DECORATION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TEAM_DECORATION);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CANOPY_SUPPLIER);
                ai.setJavaName(ATTR_CANOPY_SUPPLIER);
                ai.setColumnName(ATTR_CANOPY_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CANOPY_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AIR_CONDITIONING_SUPPLIER);
                ai.setJavaName(ATTR_AIR_CONDITIONING_SUPPLIER);
                ai.setColumnName(ATTR_AIR_CONDITIONING_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AIR_CONDITIONING_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LIGHT_BOX_SUPPLIER);
                ai.setJavaName(ATTR_LIGHT_BOX_SUPPLIER);
                ai.setColumnName(ATTR_LIGHT_BOX_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LIGHT_BOX_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CABINTE_SUPPLIER);
                ai.setJavaName(ATTR_CABINTE_SUPPLIER);
                ai.setColumnName(ATTR_CABINTE_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CABINTE_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LED_SCREEN_SUPPLIER);
                ai.setJavaName(ATTR_LED_SCREEN_SUPPLIER);
                ai.setColumnName(ATTR_LED_SCREEN_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LED_SCREEN_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CHECKOUT_SUPPLIER);
                ai.setJavaName(ATTR_CHECKOUT_SUPPLIER);
                ai.setColumnName(ATTR_CHECKOUT_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CHECKOUT_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AUTOMATIC_DOOR_SUPPLIER);
                ai.setJavaName(ATTR_AUTOMATIC_DOOR_SUPPLIER);
                ai.setColumnName(ATTR_AUTOMATIC_DOOR_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AUTOMATIC_DOOR_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SHUTTER_DOOR_SUPPLIER);
                ai.setJavaName(ATTR_SHUTTER_DOOR_SUPPLIER);
                ai.setColumnName(ATTR_SHUTTER_DOOR_SUPPLIER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SHUTTER_DOOR_SUPPLIER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT1);
                ai.setJavaName(ATTR_EXT1);
                ai.setColumnName(ATTR_EXT1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SHOP_VOLUME);
                ai.setJavaName(ATTR_SHOP_VOLUME);
                ai.setColumnName(ATTR_SHOP_VOLUME);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_SHOP_VOLUME);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EXT2);
                ai.setJavaName(ATTR_EXT2);
                ai.setColumnName(ATTR_EXT2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EXT2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATUS);
                ai.setJavaName(ATTR_STATUS);
                ai.setColumnName(ATTR_STATUS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATUS);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public SHOP_MASTER_ENGDEPTBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getSHOP_ID()
    {
        return getStringProperty(ATTR_SHOP_ID);
    }

    public void setSHOP_ID(String value)
    {
        setProperty(ATTR_SHOP_ID, value, 0);
    }

    public String getFORM_ID()
    {
        return getStringProperty(ATTR_FORM_ID);
    }

    public void setFORM_ID(String value)
    {
        setProperty(ATTR_FORM_ID, value, 0);
    }

    public String getUSER_NAME()
    {
        return getStringProperty(ATTR_USER_NAME);
    }

    public void setUSER_NAME(String value)
    {
        setProperty(ATTR_USER_NAME, value, 0);
    }

    public String getUSER_CODE()
    {
        return getStringProperty(ATTR_USER_CODE);
    }

    public void setUSER_CODE(String value)
    {
        setProperty(ATTR_USER_CODE, value, 0);
    }

    public String getDEPARTMENT_CODE()
    {
        return getStringProperty(ATTR_DEPARTMENT_CODE);
    }

    public void setDEPARTMENT_CODE(String value)
    {
        setProperty(ATTR_DEPARTMENT_CODE, value, 0);
    }

    public String getDEPARTMENT_NAME()
    {
        return getStringProperty(ATTR_DEPARTMENT_NAME);
    }

    public void setDEPARTMENT_NAME(String value)
    {
        setProperty(ATTR_DEPARTMENT_NAME, value, 0);
    }

    public String getCOMPANY_CODE()
    {
        return getStringProperty(ATTR_COMPANY_CODE);
    }

    public void setCOMPANY_CODE(String value)
    {
        setProperty(ATTR_COMPANY_CODE, value, 0);
    }

    public String getCOMPANY_NAME()
    {
        return getStringProperty(ATTR_COMPANY_NAME);
    }

    public void setCOMPANY_NAME(String value)
    {
        setProperty(ATTR_COMPANY_NAME, value, 0);
    }

    public java.util.Date getAPPLICATION_DATE()
    {
        return getDateTimestampProperty(ATTR_APPLICATION_DATE);
    }

    public void setAPPLICATION_DATE(java.util.Date value)
    {
        setProperty(ATTR_APPLICATION_DATE, value, 0);
    }

    public String getONEROOM()
    {
        return getStringProperty(ATTR_ONEROOM);
    }

    public void setONEROOM(String value)
    {
        setProperty(ATTR_ONEROOM, value, 0);
    }

    public String getONEROOM_NAME()
    {
        return getStringProperty(ATTR_ONEROOM_NAME);
    }

    public void setONEROOM_NAME(String value)
    {
        setProperty(ATTR_ONEROOM_NAME, value, 0);
    }

    public String getBUSINESS_SPACE()
    {
        return getStringProperty(ATTR_BUSINESS_SPACE);
    }

    public void setBUSINESS_SPACE(String value)
    {
        setProperty(ATTR_BUSINESS_SPACE, value, 0);
    }

    public String getAFTER_WAREHOUSE_AREA()
    {
        return getStringProperty(ATTR_AFTER_WAREHOUSE_AREA);
    }

    public void setAFTER_WAREHOUSE_AREA(String value)
    {
        setProperty(ATTR_AFTER_WAREHOUSE_AREA, value, 0);
    }

    public String getCOUNTER_TO_DOOR()
    {
        return getStringProperty(ATTR_COUNTER_TO_DOOR);
    }

    public void setCOUNTER_TO_DOOR(String value)
    {
        setProperty(ATTR_COUNTER_TO_DOOR, value, 0);
    }

    public String getPOSITIVE_DIRECTION()
    {
        return getStringProperty(ATTR_POSITIVE_DIRECTION);
    }

    public void setPOSITIVE_DIRECTION(String value)
    {
        setProperty(ATTR_POSITIVE_DIRECTION, value, 0);
    }

    public String getPOSITIVE_DIRECTIONNAME()
    {
        return getStringProperty(ATTR_POSITIVE_DIRECTIONNAME);
    }

    public void setPOSITIVE_DIRECTIONNAME(String value)
    {
        setProperty(ATTR_POSITIVE_DIRECTIONNAME, value, 0);
    }

    public String getHIGH_CABINTE_NO()
    {
        return getStringProperty(ATTR_HIGH_CABINTE_NO);
    }

    public void setHIGH_CABINTE_NO(String value)
    {
        setProperty(ATTR_HIGH_CABINTE_NO, value, 0);
    }

    public String getSHOP_CABINTE_NO()
    {
        return getStringProperty(ATTR_SHOP_CABINTE_NO);
    }

    public void setSHOP_CABINTE_NO(String value)
    {
        setProperty(ATTR_SHOP_CABINTE_NO, value, 0);
    }

    public String getAATROUGH_NO()
    {
        return getStringProperty(ATTR_AATROUGH_NO);
    }

    public void setAATROUGH_NO(String value)
    {
        setProperty(ATTR_AATROUGH_NO, value, 0);
    }

    public String getBACK_CABINET_NO()
    {
        return getStringProperty(ATTR_BACK_CABINET_NO);
    }

    public void setBACK_CABINET_NO(String value)
    {
        setProperty(ATTR_BACK_CABINET_NO, value, 0);
    }

    public String getSIDE_LIGHT_BOX_SIZE()
    {
        return getStringProperty(ATTR_SIDE_LIGHT_BOX_SIZE);
    }

    public void setSIDE_LIGHT_BOX_SIZE(String value)
    {
        setProperty(ATTR_SIDE_LIGHT_BOX_SIZE, value, 0);
    }

    public String getDOOR_LIGHT_BOX_SIZE()
    {
        return getStringProperty(ATTR_DOOR_LIGHT_BOX_SIZE);
    }

    public void setDOOR_LIGHT_BOX_SIZE(String value)
    {
        setProperty(ATTR_DOOR_LIGHT_BOX_SIZE, value, 0);
    }

    public String getADVERTISEMENT_LOCATION()
    {
        return getStringProperty(ATTR_ADVERTISEMENT_LOCATION);
    }

    public void setADVERTISEMENT_LOCATION(String value)
    {
        setProperty(ATTR_ADVERTISEMENT_LOCATION, value, 0);
    }

    public double getLATTICE_NO()
    {
        return getDoubleProperty(ATTR_LATTICE_NO);
    }

    public void setLATTICE_NO(double value)
    {
        setProperty(ATTR_LATTICE_NO, value, 0);
    }

    public double getENTRANCE_NO()
    {
        return getDoubleProperty(ATTR_ENTRANCE_NO);
    }

    public void setENTRANCE_NO(double value)
    {
        setProperty(ATTR_ENTRANCE_NO, value, 0);
    }

    public java.util.Date getDECORATION_END_DATE()
    {
        return getDateTimestampProperty(ATTR_DECORATION_END_DATE);
    }

    public void setDECORATION_END_DATE(java.util.Date value)
    {
        setProperty(ATTR_DECORATION_END_DATE, value, 0);
    }

    public String getDECORATION_STYLE()
    {
        return getStringProperty(ATTR_DECORATION_STYLE);
    }

    public void setDECORATION_STYLE(String value)
    {
        setProperty(ATTR_DECORATION_STYLE, value, 0);
    }

    public String getDECORATION_STYLENAME()
    {
        return getStringProperty(ATTR_DECORATION_STYLENAME);
    }

    public void setDECORATION_STYLENAME(String value)
    {
        setProperty(ATTR_DECORATION_STYLENAME, value, 0);
    }

    public String getCABINTE_LAYOUT_STYLE()
    {
        return getStringProperty(ATTR_CABINTE_LAYOUT_STYLE);
    }

    public void setCABINTE_LAYOUT_STYLE(String value)
    {
        setProperty(ATTR_CABINTE_LAYOUT_STYLE, value, 0);
    }

    public String getCABINTE_LAYOUTSTYLENAME()
    {
        return getStringProperty(ATTR_CABINTE_LAYOUTSTYLENAME);
    }

    public void setCABINTE_LAYOUTSTYLENAME(String value)
    {
        setProperty(ATTR_CABINTE_LAYOUTSTYLENAME, value, 0);
    }

    public String getTEAM_DECORATION()
    {
        return getStringProperty(ATTR_TEAM_DECORATION);
    }

    public void setTEAM_DECORATION(String value)
    {
        setProperty(ATTR_TEAM_DECORATION, value, 0);
    }

    public String getCANOPY_SUPPLIER()
    {
        return getStringProperty(ATTR_CANOPY_SUPPLIER);
    }

    public void setCANOPY_SUPPLIER(String value)
    {
        setProperty(ATTR_CANOPY_SUPPLIER, value, 0);
    }

    public String getAIR_CONDITIONING_SUPPLIER()
    {
        return getStringProperty(ATTR_AIR_CONDITIONING_SUPPLIER);
    }

    public void setAIR_CONDITIONING_SUPPLIER(String value)
    {
        setProperty(ATTR_AIR_CONDITIONING_SUPPLIER, value, 0);
    }

    public String getLIGHT_BOX_SUPPLIER()
    {
        return getStringProperty(ATTR_LIGHT_BOX_SUPPLIER);
    }

    public void setLIGHT_BOX_SUPPLIER(String value)
    {
        setProperty(ATTR_LIGHT_BOX_SUPPLIER, value, 0);
    }

    public String getCABINTE_SUPPLIER()
    {
        return getStringProperty(ATTR_CABINTE_SUPPLIER);
    }

    public void setCABINTE_SUPPLIER(String value)
    {
        setProperty(ATTR_CABINTE_SUPPLIER, value, 0);
    }

    public String getLED_SCREEN_SUPPLIER()
    {
        return getStringProperty(ATTR_LED_SCREEN_SUPPLIER);
    }

    public void setLED_SCREEN_SUPPLIER(String value)
    {
        setProperty(ATTR_LED_SCREEN_SUPPLIER, value, 0);
    }

    public String getCHECKOUT_SUPPLIER()
    {
        return getStringProperty(ATTR_CHECKOUT_SUPPLIER);
    }

    public void setCHECKOUT_SUPPLIER(String value)
    {
        setProperty(ATTR_CHECKOUT_SUPPLIER, value, 0);
    }

    public String getAUTOMATIC_DOOR_SUPPLIER()
    {
        return getStringProperty(ATTR_AUTOMATIC_DOOR_SUPPLIER);
    }

    public void setAUTOMATIC_DOOR_SUPPLIER(String value)
    {
        setProperty(ATTR_AUTOMATIC_DOOR_SUPPLIER, value, 0);
    }

    public String getSHUTTER_DOOR_SUPPLIER()
    {
        return getStringProperty(ATTR_SHUTTER_DOOR_SUPPLIER);
    }

    public void setSHUTTER_DOOR_SUPPLIER(String value)
    {
        setProperty(ATTR_SHUTTER_DOOR_SUPPLIER, value, 0);
    }

    public String getEXT1()
    {
        return getStringProperty(ATTR_EXT1);
    }

    public void setEXT1(String value)
    {
        setProperty(ATTR_EXT1, value, 0);
    }

    public double getSHOP_VOLUME()
    {
        return getDoubleProperty(ATTR_SHOP_VOLUME);
    }

    public void setSHOP_VOLUME(double value)
    {
        setProperty(ATTR_SHOP_VOLUME, value, 0);
    }

    public String getEXT2()
    {
        return getStringProperty(ATTR_EXT2);
    }

    public void setEXT2(String value)
    {
        setProperty(ATTR_EXT2, value, 0);
    }

    public String getSTATUS()
    {
        return getStringProperty(ATTR_STATUS);
    }

    public void setSTATUS(String value)
    {
        setProperty(ATTR_STATUS, value, 0);
    }

    public static BusObjectIterator<com.laiyifen.shop.SHOP_MASTER_ENGDEPT> getNextShopMasterEngdeptObjects(String FORM_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"SHOP_MASTER_ENGDEPT\" where (\"FORM_ID\" > :FORM_ID) order by \"FORM_ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("FORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, FORM_ID);//NOPMD
        query.setResultClass(SHOP_MASTER_ENGDEPT.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.shop.SHOP_MASTER_ENGDEPT> getPreviousShopMasterEngdeptObjects(String FORM_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"SHOP_MASTER_ENGDEPT\" where (\"FORM_ID\" < :FORM_ID) order by \"FORM_ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("FORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, FORM_ID);//NOPMD
        query.setResultClass(SHOP_MASTER_ENGDEPT.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.laiyifen.shop.SHOP_MASTER_ENGDEPT getShopMasterEngdeptObject(String FORM_ID)
    {
        String queryText = "select * from \"SHOP_MASTER_ENGDEPT\" where \"FORM_ID\" = :FORM_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("FORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, FORM_ID);//NOPMD
        query.setResultClass(SHOP_MASTER_ENGDEPT.class);
        return (SHOP_MASTER_ENGDEPT)query.getObject();
    }


    public static BusObjectIterator<com.laiyifen.shop.SHOP_MASTER_ENGDEPT> getShopMasterEngdeptObjects(String fromFORM_ID, String toFORM_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"SHOP_MASTER_ENGDEPT\" where \"FORM_ID\" between :fromFORM_ID and :toFORM_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromFORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, fromFORM_ID);
        query.addParameter("toFORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, toFORM_ID);
        query.setResultClass(SHOP_MASTER_ENGDEPT.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.laiyifen.shop.SHOP_MASTER_ENGDEPT> getShopMasterEngdeptObjects(String fromFORM_ID, String toFORM_ID)
    {
        String queryText = "select * from \"SHOP_MASTER_ENGDEPT\" where \"FORM_ID\" between :fromFORM_ID and :toFORM_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromFORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, fromFORM_ID);
        query.addParameter("toFORM_ID", "SHOP_MASTER_ENGDEPT.FORM_ID", QueryObject.PARAM_STRING, toFORM_ID);
        query.setResultClass(SHOP_MASTER_ENGDEPT.class);
        return query.getObjects();
    }

}
