/*
  This class has been generated by the Code Generator
*/

package com.laiyifen.shop;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.DMLStatement;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.laiyifen.common.exceptions.LYFException;

public class SUPPLIERS_MASTER extends SUPPLIERS_MASTERBase
{
    public SUPPLIERS_MASTER()
    {
        this((BusObjectConfig)null);
    }

    public SUPPLIERS_MASTER(BusObjectConfig config)
    {
        super(config);
    }

    public static com.laiyifen.shop.SUPPLIERS_MASTER getSupplierInfoByShopId(String shopId)
    {
    	String queryText = "select CONTACTER,CONTACTER_PHONE from \"SUPPLIERS_MASTER\" where \"SHOP_ID\" = :SHOP_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SHOP_ID", "SUPPLIERS_MASTER.SHOP_ID", QueryObject.PARAM_STRING, shopId);
        query.setResultClass(SUPPLIERS_MASTER.class);
        return (SUPPLIERS_MASTER)query.getObject();
    }

    public static void updateSAPNoByShopId(String shopId, String SapNo) throws LYFException
    {
    	try{
    	DMLStatement dml = new DMLStatement("UPDATE suppliers_master t SET t.sap_vendorno = '" + SapNo + "' WHERE t.shop_id = '" + shopId + "'");
		dml.execute();
    	}catch(Exception e){
    		throw new LYFException("更新SAP编码失败" + e);
    	}
    }

}
